### ISSUE TITLE
Session timeouts in a couple hours. 

### ISSUE THREAD

**Issue by velaar** [andersonshatch/midea-ac-lib#3]
Integration stops working entirely after about 4 hours spamming the following error:
 

```
Retrying API call: 'user/login'

Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
```

It seems there was some work done about it before: 
https://github.com/NeoAcheron/midea-ac-py/compare/master...Michael0yodi:master

Not sure If the fix is supposed to be in the library or on the homeassistant side.

**Comment by andersonshatch** [comment]
Those should be incorporated here I think, plus I added some changes in b9c64be520b8eafb8ddc0320e0406bd19947ef91 which helped before.
I don't experience this issue, but then I do have to disable polling with the fan_only_workaround option, so maybe that could be why.

**Comment by velaar** [comment]
Ok, sorry for the delay. Further testing with fan_only_workaround doesn't affect it. In a couple hours after the first connect if you press any button it just begins to spam 
```
Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
Retrying API call: 'user/login'
```

And this continues until hass restart.  Is there a chance that restart full doesn't get triggered in client.py?

**Comment by velaar** [comment]
Found it! The issue was on my side. For some reason it was pulling the wring midea lib. Works as expected in both modes now.
